### ISSUE TITLE
[tracking issue] Transcribe the Compiler Lecture Series into chapters

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rustc-guide#319]
- [x] Tom Tromey discusses debugging support in rustc
    - assigned to @amanjeev, #316 
    - Video: https://www.youtube.com/watch?v=elBxMRSNYr4
    - Lecture notes:
- [ ] How Salsa Works (2019.01)
    - Video: https://www.youtube.com/watch?v=_muY4HjSqVw
    - Lecture notes:
- [ ] Salsa In More Depth (2019.01)
    - Video: https://www.youtube.com/watch?v=i_IhACacPRY
    - Lecture notes:
- [ ] RLS 2.0, Salsa, and Name Resolution
    - Video: https://www.youtube.com/watch?v=Xr-rBqLr-G4
    - Lecture notes:
- [ ] Cranelift
    - Video: https://www.youtube.com/watch?v=9OIA7DTFQWU
    - Lecture notes:
- [ ] Rust analyzer guide
    - Video: https://www.youtube.com/watch?v=ANKBNiSWyfc
    - Lecture notes:
- [ ] Rust analyzer syntax trees
    - Video: https://www.youtube.com/watch?v=DGAuLWdCCAI
    - Lecture notes:
- [ ] rust-analyzer type-checker overview by flodiebold
    - Video: https://www.youtube.com/watch?v=Lmp3P9WNL8o
    - Lecture notes:
- [ ] oli-obk on miri and constant evaluation
    - Video: https://www.youtube.com/watch?v=5Pm2C1YXrvM
    - Lecture notes:
- [ ] Polonius-rustc walkthrough
    - Video: https://www.youtube.com/watch?v=i5KdU0ieb_A
    - Lecture notes:
- [ ] rustc-chalk integration overview
    - Video: https://www.youtube.com/watch?v=MBWtbDifPeU
    - Lecture notes:
- [ ] Coherence in Chalk by Sunjay Varma - Bay Area Rust Meetup
    - assigned to @juanbono
    - Video: https://www.youtube.com/watch?v=rZqS4bLPL24
    - Lecture notes:
- [ ] How the chalk-engine crate works
    - Video: https://www.youtube.com/watch?v=Ny2928cGDoM
    - Lecture notes:
- [ ] How the chalk-engine crate works 2
    - Video: https://www.youtube.com/watch?v=hmV66tB79LM
- [ ] RFC #2229 Disjoint Field Capture plan
    - Video: https://www.youtube.com/watch?v=UTXOptVMuIc
    - Lecture notes:
- [ ] closures and upvar capture
    - Video: https://www.youtube.com/watch?v=fMopdkn5-Xw
    - Lecture notes:
- [ ] blitzerr closure upvar tys
    - Video: https://www.youtube.com/watch?v=pLmVhSB-z4s
    - Lecture notes:
- [ ] Convert Closure Upvar Representation to Tuples with blitzerr
    - Video: https://www.youtube.com/watch?v=2QCuNtISoYc
    - Lecture notes:
- [ ] async-await implementation plans
    - Video: https://www.youtube.com/watch?v=xe2_whJWBC0
    - Lecture notes:
- [ ] async-await region inferencer
    - Video: https://www.youtube.com/watch?v=hlOxfkUDLPQ
    - Lecture notes:
- [ ] Universes and Lifetimes
    - Video: https://www.youtube.com/watch?v=iV1Z0xYXkck
    - Lecture notes:
- [ ] Representing types in rustc
    - assigned to @igaray 
    - Video: https://www.youtube.com/watch?v=c01TsOsr3-c
    - Lecture notes: +Ty lecture
- [ ] Polonius WG: Initialization and move tracking
    - Video: https://www.youtube.com/watch?v=ilv9V-328HI
    - Lecture notes: 

cc @spastorino

**Comment by mark-i-m** [comment]
Recording new sessions ideas


- The `ty` module -- how it works (3 votes) (coming on friday 26th)
    - The arenas, the `'tcx` and `'gcx` lifetimes
    - The `TypeFoldable` trait and the `TyRelate` trait
    - Maybe covering the basics of type inference
    - Candidates: @nikomatsakis, @varkor, perhaps @eddyb?
- HAIR, MIR, and MIR construction (3 votes)
    - Covering the definition of MIR
    - Covering the HAIR construction
    - Covering MIR building
    - (This is actively changing as part of #t-compiler/wg-mir-opt, so that's a downside, but otoh maybe the coverage of MIR building would be helpful for Place 2.0 work)
    - Candidates: @nikomatsakis, @oli, @eddyb, maybe others?
- Typeck tables and the type checker (2 votes)
    - Covering how the type checker works at a high-level and the role of the typeck tables
- HIR (1 vote)
    - Covering the role of HIR, how the HIR lowering code works
    - Candidates: @nikomatsakis, @Taylor Cramer, perhaps @eddyb?

Other ideas (some are already covered):


- Debugger integration (@tromey)
- Chalk (@nikomatsakis)
- prusti (@vakaras)
- Polonius (@nikomatsakis)
- Name resolution (@petrochenkov)
- Macro expansion (@pnkfelix, maybe?)
- RLS (@Xanewok)
- rust-analyzer (@matklad)
- rustdoc (@QuietMisdreavus)
- incremental compilation and/or salsa (@michaelwoerister, @nikomatsakis)
- Const eval
- Diagnostics
- LLVM/codegen (@nagisa, @alexcrichton )

**Comment by shepmaster** [comment]
Note that YouTube will auto generate transcriptions, which might be a good place to start.

**Comment by igaray** [comment]
ssshhhh 🤐  they think I'm hard at work!

**Comment by igaray** [comment]
In all seriousness, this is exactly what I did: 
- click on the gear icon of the youtube video player
- select 'subtitles' submenu
- select 'add subtitles' item
- select language -> 'english'
- click on 'actions' button
- select 'download'
- open .sbv file with with and create macro to delete timestamps

**Comment by igaray** [comment]
@mark-i-m Can you add 
```- [ ] How the chalk-engine crate works 2
    - Video: https://www.youtube.com/watch?v=hmV66tB79LM
```
right after "How the chalk-engine crate works" ? TY!

**Comment by eddyb** [comment]
> The arenas, the `'tcx` and `'gcx` lifetimes

@Zoxc is planning to remove that split in https://github.com/rust-lang/rust/pull/57214, FWIW.

**Comment by amanjeev** [comment]
Opened and assigned to myself 

- #352 
- #353 
- #354

**Comment by mark-i-m** [comment]
@spastorino perhaps we can play with a project now?

**Comment by spastorino** [comment]
@mark-i-m yes, hope to be able to do it today :).

**Comment by spastorino** [comment]
This is superseeded by https://github.com/rust-lang/rustc-guide/projects/2
