### ISSUE TITLE
master tracking issue

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-guide#6]
This tracking issue contains links to the issues for all the chapters and subsections of the book. It is also the main place to come to if you're looking to get started on contributing.

### How to contribute

Skim down the list below and find a chapter that looks interesting to you. It should have a link to an associated tracking issue. Click on that link and leave a comment there saying you'd like to help out (and/or start writing something).

**In general, if you don't know how the compiler works, that is not a problem!** In that case, what we will do is to schedule a bit of time for you to talk with someone who **does** know the code, or who wants to pair with you and figure it out.  Then you can work on writing up what you learned. Just cc @nikomatsakis for help.

**If you think there is a missing section please file an issue and we will consider how to fit into this outline.**

### The outline

- [x] How to build the compiler and run what you built (https://github.com/rust-lang-nursery/rustc-guide/issues/8)
- [x] Walkthrough: a typical contribution (#237)
- [x] Using the compiler testing framework (https://github.com/rust-lang-nursery/rustc-guide/issues/10)
- [x] Debugging the compiler (https://github.com/rust-lang-nursery/rustc-guide/issues/11)
- [ ] Conventions used in the compiler (https://github.com/rust-lang-nursery/rustc-guide/issues/12)
- [ ] The parser (https://github.com/rust-lang-nursery/rustc-guide/issues/13)
- [ ] Diagnostics: reporting errors and lints (https://github.com/rust-lang-nursery/rustc-guide/issues/14)
- [ ] Macro expansion (https://github.com/rust-lang-nursery/rustc-guide/issues/15)
- [ ] Name resolution (https://github.com/rust-lang-nursery/rustc-guide/issues/16)
- [ ] HIR and HIR lowering (https://github.com/rust-lang-nursery/rustc-guide/issues/17)
- [x] Representing types (`ty` module in depth)
- [x] Type inference
- [x] Trait resolution (#52, #70 )
- [ ] Type checking
- [x] MIR construction
- [x] MIR borrowck (#67 )
- [ ] MIR optimizations
- [x] MIRI (#30, #45)
- [ ] trans: generating LLVM IR (#89)
- [x] Glossary

**Comment by nikomatsakis** [comment]
Note: this conversation is locked to keep this tracking issue tidy.

**Comment by mark-i-m** [comment]
@nikomatsakis I think this issue is getting rather out of date. At this point, it seem like all of these topics have made it into the table of contents of the book; it's just a matter of fleshing out the chapters.

Should we close this issue?
